-- Daily, user-owned weigh-ins with an optional private progress photo, plus
-- the structured micronutrient report produced by the scheduled weekly
-- analysis harness.

create table public.weight_checkins (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  local_day date not null,
  weight_kg numeric(6,2) not null,
  progress_photo_path text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, local_day),
  constraint weight_checkins_weight_range_check
    check (weight_kg between 20 and 500),
  constraint weight_checkins_progress_photo_owned_check check (
    progress_photo_path is null
    or (
      split_part(progress_photo_path, '/', 1) = user_id::text
      and progress_photo_path ~ (
        '^' || user_id::text
        || '/[0-9]{4}-[0-9]{2}-[0-9]{2}/progress-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.]jpg$'
      )
      and length(progress_photo_path) <= 160
    )
  )
);

comment on table public.weight_checkins is
  'One user-owned weight observation per local calendar day with an optional private progress photo.';

create index weight_checkins_user_day_desc_idx
  on public.weight_checkins (user_id, local_day desc);

drop trigger if exists weight_checkins_set_updated_at on public.weight_checkins;
create trigger weight_checkins_set_updated_at
before update on public.weight_checkins
for each row execute function private.set_updated_at();

alter table public.weight_checkins enable row level security;

create policy weight_checkins_select_own on public.weight_checkins
for select to authenticated
using ((select auth.uid()) = user_id);

create policy weight_checkins_insert_own on public.weight_checkins
for insert to authenticated
with check ((select auth.uid()) = user_id);

create policy weight_checkins_update_own on public.weight_checkins
for update to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy weight_checkins_delete_own on public.weight_checkins
for delete to authenticated
using ((select auth.uid()) = user_id);

revoke all on public.weight_checkins
  from public, anon, authenticated, service_role;
grant select, insert, update, delete on public.weight_checkins to authenticated;
grant select, insert, update, delete on public.weight_checkins to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'weight-checkin-photos',
  'weight-checkin-photos',
  false,
  4194304,
  array['image/jpeg']
)
on conflict (id) do update
set public = false,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

create policy weight_checkin_photos_select_own on storage.objects
for select to authenticated
using (
  bucket_id = 'weight-checkin-photos'
  and (storage.foldername(name))[1] = (select auth.uid())::text
  and name ~ (
    '^' || (select auth.uid())::text
    || '/[0-9]{4}-[0-9]{2}-[0-9]{2}/progress-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.]jpg$'
  )
);

create policy weight_checkin_photos_insert_own on storage.objects
for insert to authenticated
with check (
  bucket_id = 'weight-checkin-photos'
  and (storage.foldername(name))[1] = (select auth.uid())::text
  and name ~ (
    '^' || (select auth.uid())::text
    || '/[0-9]{4}-[0-9]{2}-[0-9]{2}/progress-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.]jpg$'
  )
);

create policy weight_checkin_photos_delete_own on storage.objects
for delete to authenticated
using (
  bucket_id = 'weight-checkin-photos'
  and (storage.foldername(name))[1] = (select auth.uid())::text
  and name ~ (
    '^' || (select auth.uid())::text
    || '/[0-9]{4}-[0-9]{2}-[0-9]{2}/progress-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}[.]jpg$'
  )
);

alter table public.weekly_summaries
  add column micronutrient_report jsonb not null default '{}'::jsonb;

alter table public.weekly_summaries
  add constraint weekly_summaries_micronutrient_report_object_check
    check (jsonb_typeof(micronutrient_report) = 'object');

comment on column public.weekly_summaries.micronutrient_report is
  'Structured weekly vitamin, mineral, fiber, and fatty-acid estimates generated by independent specialists and a synthesis pass.';
